apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-webui-proxy
  namespace: pipecache
  labels:
    app: sd-webui-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sd-webui-proxy
  template:
    metadata:
      labels:
        app: sd-webui-proxy
    spec:
      containers:
      - name: sd-webui-proxy
        image: k.harbor.siat.ac.cn/pels/sd-webui:v0.10
        ports:
        - containerPort: 7860
          name: http
        env:
        - name: SD_API_URL
          value: "http://sd-api-service:7860"  # 指向后端SD API服务
        - name: GRADIO_SERVER_NAME
          value: "0.0.0.0"
        - name: GRADIO_SERVER_PORT
          value: "7860"
        - name: SD_API_TIMEOUT
          value: "600"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /sdapi/v1/progress
            port: 7860
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /sdapi/v1/progress
            port: 7860
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sd-webui-proxy-service
  namespace: pipecache
  labels:
    app: sd-webui-proxy
spec:
  type: NodePort
  ports:
  - port: 7860
    targetPort: 7860
    nodePort: 32001
    protocol: TCP
    name: http
  selector:
    app: sd-webui-proxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sd-webui-proxy-ingress
  namespace: pipecache
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
  - host: sd-webui.yourdomain.com  # 替换为您的域名
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sd-webui-proxy-service
            port:
              number: 7860
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sd-webui-proxy-hpa
  namespace: pipecache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sd-webui-proxy
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
